-- MySQL Script generated by MySQL Workbench
-- Thu Jan 26 14:36:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Membre` (
  `idMembre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idMembre`),
  INDEX `fk_Membre_Role1_idx` (`Role_idRole` ASC) ,
  CONSTRAINT `fk_Membre_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Timbre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Timbre` (
  `idTimbre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `dimension` VARCHAR(45) NULL,
  `Image_idImage` INT NOT NULL,
  PRIMARY KEY (`idTimbre`),
  INDEX `fk_Timbre_Image1_idx` (`Image_idImage` ASC) ,
  CONSTRAINT `fk_Timbre_Image1`
    FOREIGN KEY (`Image_idImage`)
    REFERENCES `Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Timer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Timer` (
  `idTimer` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idTimer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enchere` (
  `Membre_idMembre` INT NOT NULL,
  `Timbre_idTimbre` INT NOT NULL,
  `Status_idStatus` INT NOT NULL,
  `Timer_idTimer` INT NOT NULL,
  PRIMARY KEY (`Membre_idMembre`, `Timbre_idTimbre`),
  INDEX `fk_Membre_has_Timbre_Timbre1_idx` (`Timbre_idTimbre` ASC) ,
  INDEX `fk_Membre_has_Timbre_Membre1_idx` (`Membre_idMembre` ASC) ,
  INDEX `fk_Enchere_Status1_idx` (`Status_idStatus` ASC) ,
  INDEX `fk_Enchere_Timer1_idx` (`Timer_idTimer` ASC) ,
  CONSTRAINT `fk_Membre_has_Timbre_Membre1`
    FOREIGN KEY (`Membre_idMembre`)
    REFERENCES `Membre` (`idMembre`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membre_has_Timbre_Timbre1`
    FOREIGN KEY (`Timbre_idTimbre`)
    REFERENCES `Timbre` (`idTimbre`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enchere_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `Status` (`idStatus`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enchere_Timer1`
    FOREIGN KEY (`Timer_idTimer`)
    REFERENCES `Timer` (`idTimer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mise` (
  `idMise` INT NOT NULL AUTO_INCREMENT,
  `mise` DOUBLE NOT NULL,
  `Membre_idMembre` INT NOT NULL,
  `Enchere_Membre_idMembre` INT NOT NULL,
  `Enchere_Timbre_idTimbre` INT NOT NULL,
  PRIMARY KEY (`idMise`, `Membre_idMembre`, `Enchere_Membre_idMembre`, `Enchere_Timbre_idTimbre`),
  INDEX `fk_Mise_Membre1_idx` (`Membre_idMembre` ASC) ,
  INDEX `fk_Mise_Enchere1_idx` (`Enchere_Membre_idMembre` ASC, `Enchere_Timbre_idTimbre` ASC) ,
  CONSTRAINT `fk_Mise_Membre1`
    FOREIGN KEY (`Membre_idMembre`)
    REFERENCES `Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mise_Enchere1`
    FOREIGN KEY (`Enchere_Membre_idMembre` , `Enchere_Timbre_idTimbre`)
    REFERENCES `Enchere` (`Membre_idMembre` , `Timbre_idTimbre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stampee`.`Favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Favoris` (
  `Membre_idMembre` INT NOT NULL,
  `Enchere_Membre_idMembre` INT NOT NULL,
  `Enchere_Timbre_idTimbre` INT NOT NULL,
  PRIMARY KEY (`Membre_idMembre`, `Enchere_Membre_idMembre`, `Enchere_Timbre_idTimbre`),
  INDEX `fk_Membre_has_Enchere_Enchere1_idx` (`Enchere_Membre_idMembre` ASC, `Enchere_Timbre_idTimbre` ASC) ,
  INDEX `fk_Membre_has_Enchere_Membre1_idx` (`Membre_idMembre` ASC) ,
  CONSTRAINT `fk_Membre_has_Enchere_Membre1`
    FOREIGN KEY (`Membre_idMembre`)
    REFERENCES `Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membre_has_Enchere_Enchere1`
    FOREIGN KEY (`Enchere_Membre_idMembre` , `Enchere_Timbre_idTimbre`)
    REFERENCES `Enchere` (`Membre_idMembre` , `Timbre_idTimbre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
